char index_html[] =
"<html>"
  "<head>"
    "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">"
    "<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" integrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\" crossorigin=\"anonymous\">"
    "<script src=\"app.js\"></script>"
  "</head>"
  "<body>"
    "<div id=\"top-row\" class=\"row\">"
      "<div class=\"col-md-2 col-xs-2\"></div>"
      "<div id=\"title\" class=\"col-md-8 col-xs-8 center\">Home</div>"
      "<div class=\"col-md-2 col-xs-2\"></div>"
    "</div>"
    "<div id=\"thermometer\">"
      "<div class=\"row\">"
	"<div class=\"col-md-4\"></div>"
	"<div class=\"col-md-4 center\"><button class=\"btn btn-default btn-circle btn-xl\">75</button></div>"
	"<div class=\"col-md-4\"></div>"
      "</div>"
      "<div class=\"row\">"
	"<div class=\"col-md-4\"></div>"
	"<div class=\"col-md-1 center\"><button class=\"btn btn-default btn-circle btn-l\">75</button></div>"
	"<div class=\"col-md-2 center\"><button class=\"btn btn-default btn-circle btn-l\">75</button></div>"
	"<div class=\"col-md-1 center\"><button class=\"btn btn-default btn-circle btn-l\">75</button></div>"
	"<div class=\"col-md-4\"></div>"
      "</div>"
    "</div>"
 "</body>"
"</html>";
char index_css[] =
"body {"
    "height: 100%;"
    "background: linear-gradient(lightblue, white);"
"}"

".center {"
    "text-align: center;"
"}"

".btn.btn-circle {"
    "text-align: center;"
    "border-radius: 50%;"
    "background: linear-gradient(to top, grey, white);"
"}"

".btn-circle.btn-xl {"
    "width:300px;"
    "height:300px;"
    "font-size:100px;"
"}"
".btn-circle.btn-l {"
    "width:150px;"
    "height:150px;"
    "font-size:75px;"
"}"
".btn-circle.btn-sm {"
    "width:30px;"
    "height:30px;"
    "font-size:10px;"
"}"
"#title{"
    "font-size:30px;"
"}"
".vertical-center{"
    "min-height:100%;"
    "min-height:100vh;"

    "display: flex;"
    "align-items: center;"
"}";
char index_js[] ="";
